[[ObjectModel]]
Name = "型线生成"
Category = "分类"

[[ObjectModel.UnitLayers]]
Name = "十一参数"
ParameterNames = [
    "Chord_Length",
    "Upper_Max_Width",
    "Upper_Max_Width_Loc",
    "Upper_Angle",
    "Upper_tip_coeff",
    "Upper_aft_part_shape",
    "Lower_max_width",
    "Lower_max_width_loc",
    "Lower_Angle",
    "Lower_tip_coeff",
    "Lower_aft_part_shape",
    "Tangent_Leading_Edge",
    "Z_height",
]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Chord_Length"
DisplayName = "截面弦长"
Type = "float"
Data = "[1.1,2.2,3.3]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Max_Width"
DisplayName = "叶背最大厚度/相对弦长"
Type = "int"
Data = "[1,2,3]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Max_Width_Loc"
DisplayName = "叶背最大厚度位置"
Type = "string"
Data = "[\"12,3\",\"23,4\",\"34,5\"]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Angle"
DisplayName = "叶背与尾缘夹角"
Type = "List<float>"
Data = "[[1.1,2.2,3.3],[1.1,2.2,3.3]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_tip_coeff"
DisplayName = "叶背-前缘外形因数"
Type = "List<int>"
Data = "[[1,2,3],[1,2,3]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_aft_part_shape"
DisplayName = "扩散点位置/或外形饱满度"
Type = "List<string>"
Data = "[[\"12,3\",\"23,4\"],[\"12,3\",\"23,4\"]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_max_width"
DisplayName = "叶盆最大厚度/相对弦长"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_max_width_loc"
DisplayName = "叶盆最大厚度位置"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_Angle"
DisplayName = "叶盆与尾缘夹角"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_tip_coeff"
DisplayName = "叶背-前缘外形因数"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_aft_part_shape"
DisplayName = "扩散点位置/或外形饱满度"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Tangent_Leading_Edge"
DisplayName = "前缘切向夹角"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Z_height"
DisplayName = "型线数据"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers]]
Name = "型线"
ParameterNames = ["Points"]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Points"
DisplayName = "型线点坐标（多个）"
Type = "list<Coordinate>"
Data = "[]"
[[ObjectModel.UnitLayers]]
Name = "Coordinate坐标系单元"
ParameterNames = ["x", "y", "z"]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "x"
DisplayName = "x"
Type = "float"
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "y"
DisplayName = "y"
Type = "float"
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "z"
DisplayName = "z"
Type = "float"
Data = "[]"
[[ObjectModel]]
Name = "型线生成"
Category = "分类"

[[ObjectModel.UnitLayers]]
Name = "十一参数"
ParameterNames = [
    "Chord_Length",
    "Upper_Max_Width",
    "Upper_Max_Width_Loc",
    "Upper_Angle",
    "Upper_tip_coeff",
    "Upper_aft_part_shape",
    "Lower_max_width",
    "Lower_max_width_loc",
    "Lower_Angle",
    "Lower_tip_coeff",
    "Lower_aft_part_shape",
    "Tangent_Leading_Edge",
    "Z_height",
]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Chord_Length"
DisplayName = "截面弦长"
Type = "float"
Data = "[1.1,2.2,3.3]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Max_Width"
DisplayName = "叶背最大厚度/相对弦长"
Type = "int"
Data = "[1,2,3]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Max_Width_Loc"
DisplayName = "叶背最大厚度位置"
Type = "string"
Data = "[\"12,3\",\"23,4\",\"34,5\"]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_Angle"
DisplayName = "叶背与尾缘夹角"
Type = "List<float>"
Data = "[[1.1,2.2,3.3],[1.1,2.2,3.3]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_tip_coeff"
DisplayName = "叶背-前缘外形因数"
Type = "List<int>"
Data = "[[1,2,3],[1,2,3]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Upper_aft_part_shape"
DisplayName = "扩散点位置/或外形饱满度"
Type = "List<string>"
Data = "[[\"12,3\",\"23,4\"],[\"12,3\",\"23,4\"]]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_max_width"
DisplayName = "叶盆最大厚度/相对弦长"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_max_width_loc"
DisplayName = "叶盆最大厚度位置"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_Angle"
DisplayName = "叶盆与尾缘夹角"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_tip_coeff"
DisplayName = "叶背-前缘外形因数"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Lower_aft_part_shape"
DisplayName = "扩散点位置/或外形饱满度"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Tangent_Leading_Edge"
DisplayName = "前缘切向夹角"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Z_height"
DisplayName = "型线数据"
Type = ""
Data = "[]"
[[ObjectModel.UnitLayers]]
Name = "型线"
ParameterNames = ["Points"]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "Points"
DisplayName = "型线点坐标（多个）"
Type = "list<Coordinate>"
Data = "[]"
[[ObjectModel.UnitLayers]]
Name = "Coordinate坐标系单元"
ParameterNames = ["x", "y", "z"]

[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "x"
DisplayName = "x"
Type = "float"
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "y"
DisplayName = "y"
Type = "float"
Data = "[]"
[[ObjectModel.UnitLayers.ParameterLayers]]
Name = "z"
DisplayName = "z"
Type = "float"
Data = "[]"
